package br.com.caelum.vraptor.html.example.page;

import static br.com.caelum.vraptor.html.PageAttributeFactory.attrs;
import static br.com.caelum.vraptor.html.PageAttributeFactory.href;
import static br.com.caelum.vraptor.html.PageTagFactory.a;
import static br.com.caelum.vraptor.html.PageTagFactory.body;
import static br.com.caelum.vraptor.html.PageTagFactory.head;
import static br.com.caelum.vraptor.html.PageTagFactory.html;
import static br.com.caelum.vraptor.html.PageTagFactory.p;
import static br.com.caelum.vraptor.html.PageTagFactory.span;
import static br.com.caelum.vraptor.html.PageTagFactory.text;
import static br.com.caelum.vraptor.html.PageTagFactory.title;
import static br.com.caelum.vraptor.html.UrlFactory.to;
import static br.com.caelum.vraptor.html.UrlFactory.url;
import br.com.caelum.vraptor.html.Page;
import br.com.caelum.vraptor.html.Url;
import br.com.caelum.vraptor.html.example.ExampleController;
import br.com.caelum.vraptor.html.example.Person;
import br.com.caelum.vraptor.html.tags.Html;

public class IndexPage implements Page {

	public Html render() {
		Url page2 = url(); to(ExampleController.class).page2();
		Url table = url(); to(ExampleController.class).listing();
		Url dontClick = url(to(ExampleController.class).test());
		Url google = url("http://google.com");

		Person person = new Person();
		return html(
				head(
					title("Page generated by VRaptor's HTML DSL")
				),
				body(
					p(
						text("This page has a "),
						a(attrs(href(page2)), "complex link"),
						span(" to another page")
					),
					p(
						text("To "),
						a(attrs(href(table)), "a page with a list")
					),
					p(
						text("And for "),
						a(attrs(href(google)), "Google")
					),
					p(
						text("And yet "),
						a(attrs(href(dontClick)), "a link you should not click")
					)
					// TODO make the following work
					//formFor(person, with(person).getName(), with(person).getSex())
				)
			);
	}
}
