package br.com.caelum.vraptor.html.example.page;

import static br.com.caelum.vraptor.html.Linker.link;
import static br.com.caelum.vraptor.html.Linker.to;
import static br.com.caelum.vraptor.html.PageTagFactory.a;
import static br.com.caelum.vraptor.html.PageTagFactory.attrs;
import static br.com.caelum.vraptor.html.PageTagFactory.body;
import static br.com.caelum.vraptor.html.PageTagFactory.head;
import static br.com.caelum.vraptor.html.PageTagFactory.href;
import static br.com.caelum.vraptor.html.PageTagFactory.html;
import static br.com.caelum.vraptor.html.PageTagFactory.p;
import static br.com.caelum.vraptor.html.PageTagFactory.span;
import static br.com.caelum.vraptor.html.PageTagFactory.text;
import static br.com.caelum.vraptor.html.PageTagFactory.title;
import br.com.caelum.vraptor.html.Link;
import br.com.caelum.vraptor.html.Page;
import br.com.caelum.vraptor.html.example.ExampleController;
import br.com.caelum.vraptor.html.tags.Html;

public class IndexPage implements Page {

	public Html render() {
		Link page2 = link(); to(ExampleController.class).page2();
		Link table = link(); to(ExampleController.class).listing();
		Link google = link("http://google.com");

		return html(
				head(
					title("Page generated by VRaptor's HTML DSL")
				),
				body(
					p(
						text("This page has a "),
						a(attrs(href(page2)), "complex link"),
						span(" to another page")
					),
					p(
						text("To "),
						a(attrs(href(table)), "a page with a table")
					),
					p(
						text("And for "),
						a(attrs(href(google)), "Google")
					),
					p(
						text("And yet "),
						a(attrs(href(link(to(ExampleController.class).test()))), "a link you should not click")
					)
				)
			);
	}
}
